version: "3"

services:
  application:
    build:
      context: docker/application
    container_name: demo-backend
    working_dir: /var/www
    env_file:
    - .env
    volumes:
    - ./:/var/www
    links:
    - queue:queue
    - db:db
    command: ["/tools/wait-for-it.sh", "--timeout=5", "queue:5672", "--", "/tools/entrypoint.sh"]

  queue:
    image: rabbitmq:3.7.7-management-alpine
    container_name: demo-queue
    restart: always
    ports:
    - 5672:5672
    - 15672:15672
    environment:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 512MiB
      RABBITMQ_ERLANG_COOKIE: f6fAjy5yes
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

  db:
    image: postgres:9.6
    container_name: demo-db
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_USER: demo
    ports:
    - 5432:5432
