services:

  # Default logger instance
  Psr\Log\LoggerInterface:
    public: true
    factory: 'Desperado\ServiceBus\Infrastructure\Logger\DefaultLoggerFactory:build'
    arguments:
      $entryPointName: '%service_bus.entry_point%'
      $environment: '@Desperado\ServiceBus\Environment'
      $logLevel: '%app.log_level%'

  # Create database schema
  ServiceBusDemo\App\Storage\StorageSchemaBuilder:
    public: true
    arguments:
      $applicationAdapter: '@Desperado\ServiceBus\Infrastructure\Storage\StorageAdapter'
