services:

  # Default logger instance
  Psr\Log\LoggerInterface:
    factory: 'Desperado\ServiceBus\Logger\DefaultLoggerFactory:build'
    arguments:
      $entryPointName: '%service_bus.entry_point%'
      $environment: '@Desperado\ServiceBus\Environment'
      $logLevel: '%app.log_level%'