services:
  # Generate PostgreSQL schema for service-bus components
  postgresql_schema_builder:
    class: PostgreSQLSchemaBuilder
    public: true
    arguments:
      $adapter: '@Desperado\ServiceBus\Infrastructure\Storage\StorageAdapter'

  App\Vehicle\Brand\VehicleBrandFinder:
    arguments:
      $adapter: '@Desperado\ServiceBus\Infrastructure\Storage\StorageAdapter'