services:
  # Generate PostgreSQL schema for service-bus components
  postgresql_schema_builder:
    class: PostgreSQLSchemaBuilder
    public: true
    arguments:
      $adapter: '@Desperado\ServiceBus\Infrastructure\Storage\StorageAdapter'

  App\Driver\Document\DocumentFileManager:
    arguments:
      $storageDirectory: '%app.driver.document.images_path%'

  App\Vehicle\Brand\VehicleBrandFinder:
    arguments:
      $adapter: '@Desperado\ServiceBus\Infrastructure\Storage\StorageAdapter'